server:
  port: 8080

logging:
  level:
    web: DEBUG
    org.caohh.albol.mapper: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://129.28.30.208:3306/albol?serverTimezone=Asia/Shanghai
    username: root
    password: CAOhh@123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      auto-commit: true
      idle-timeout: 60000
      pool-name: HikariPool
      max-lifetime: 0
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone:
      GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.caohh.albol.model