package org.caohh.albol.model;

import java.util.Date;
import java.util.List;
import javax.annotation.Generated;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 */
public class User {
    /**
     * Database Column Remarks:
     * ID
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user.id")
    private Long id;

    /**
     * Database Column Remarks:
     * 账号
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user.name")
    private String name;

    /**
     * Database Column Remarks:
     * 密码
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user.password")
    private String password;

    /**
     * Database Column Remarks:
     * 创建时间
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user.created_time")
    private Date createdTime;

    /**
     * Database Column Remarks:
     * 昵称
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user.username")
    private String username;

    /**
     * Database Column Remarks:
     * 头像
     */
    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user.avatar")
    private String avatar;

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user.id")
    public Long getId() {
        return id;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user.name")
    public String getName() {
        return name;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user.name")
    public void setName(String name) {
        this.name = name;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user.password")
    public String getPassword() {
        return password;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user.password")
    public void setPassword(String password) {
        this.password = password;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user.created_time")
    public Date getCreatedTime() {
        return createdTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user.created_time")
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user.username")
    public String getUsername() {
        return username;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user.username")
    public void setUsername(String username) {
        this.username = username;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user.avatar")
    public String getAvatar() {
        return avatar;
    }

    @Generated(value = "org.mybatis.generator.api.MyBatisGenerator", comments = "Source field: user.avatar")
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    private List<Role> roleList;

    private List<String> roles;

    public List<Role> getRoleList() {
        return roleList;
    }

    public void setRoleList(List<Role> roleList) {
        this.roleList = roleList;
    }

    public void setRoles(List<String> roles) {
        this.roles = roles;
    }

    public List<String> getRoles() {
        return roles;
    }

}